global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["10.188.149.94:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["10.188.149.122:9100", "10.188.149.123:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["10.188.149.122:9100", "10.188.149.123:9100"]

rule_files:
  - prometheus_alerts_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 192.168.0.1:9093
